global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'traefik'
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'drupal'
    metrics_path: 
    static_configs:
      - targets: ['drupal:80']

  - job_name: 'moodle'
    metrics_path: 
    static_configs:
      - targets: ['moodle:80']

  - job_name: 'nextcloud'
    metrics_path: /metrics
    static_configs:
      - targets: ['nextcloud:80']

  - job_name: 'n8n'
    static_configs:
      - targets: ['n8n:5678']

  - job_name: 'keycloak'
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: 'postgres_databases'
    static_configs:
      - targets: ['drupal-db:5432', 'nextcloud-db:5432', 'keycloak-db:5432', 'n8n-db:5432']

  - job_name: 'moodle-db'
    static_configs:
      - targets: ['mysqld-exporter:9104']